version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=annotations
      - MYSQL_USER=annotation_user
      - MYSQL_PASSWORD=
    depends_on:
      - mysql

  frontend:
    build: ./ge-health
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: annotations
      MYSQL_USER: annotation_user
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/annotations_structure.sql:/docker-entrypoint-initdb.d/annotations_structure.sql


networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
