/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ImageGallery.module.css";

function DateSelector() {
  return (
    <div className={styles.dateSelector}>
      <label htmlFor="dateInput" className={styles.dateSelectorLabel}>
        <span className={styles.selectValue}>09 /20 /2024 10:43</span>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/da15360bec259007baad36ea2b03b02d4059fe8d55ac08ed48a582497c1e0a1c?placeholderIfAbsent=true&apiKey=536ced9e0c9a4584a7ff64aa811182cc"
          alt=""
          className={styles.dateSelectorIcon}
        />
      </label>
      <input
        type="date"
        id="dateInput"
        className={styles["visually-hidden"]}
        aria-label="Select date"
      />
    </div>
  );
}

export default DateSelector;
