/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ImageGallery.module.css";

function ImagePreview() {
  return (
    <div className={styles.imagePreview}>
      <div className={styles.previewIndicator} />
    </div>
  );
}

export default ImagePreview;
