/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ImageGallery.module.css";
import InfoBar from "./InfoBar";
import TopBar from "./TopBar";
import ImagePreview from "./ImagePreview";
import DateSelector from "./DateSelector";
import SummarySection from "./SummarySection";


function ImageGallery() {
  return (
    <main className={styles.container}>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/c40b6ecaed3f672b57071b24b8da9c19c39f1b9ea370db6f4134f9829ff3bac0?placeholderIfAbsent=true&apiKey=536ced9e0c9a4584a7ff64aa811182cc"
        alt="Main gallery image"
        className={styles.mainImage}
      />
      <InfoBar />
      <TopBar />
      <section className={styles.contentWrapper}>
        <ImagePreview />
        <div className={styles.detailsContainer}>
          <DateSelector />
          <SummarySection />
          
        </div>
      </section>
    </main>
  );
}

export default ImageGallery;
