/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ImageGallery.module.css";

function InfoBar() {
  return (
    <div className={styles.infoBar}>
      <div className={styles.infoItem}>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/713f85ea1f6e99f9524f3e978a507a9ac91e0aa9be0e125be200f2c222a7c947?placeholderIfAbsent=true&apiKey=536ced9e0c9a4584a7ff64aa811182cc"
          alt=""
          className={styles.infoIcon}
        />
        <div className={styles.infoText}>
          <span className={styles.infoLabel}>Fetal Count:</span> 2
        </div>
      </div>
      <div className={styles.divider} />
      <div className={styles.statusIndicator}>
        <div className={styles.statusDot} />
        <div className={styles.statusText}>
          <span className={styles.infoLabel}>BP: </span>145/95 mmHg (High)
        </div>
      </div>
    </div>
  );
}

export default InfoBar;
