/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ImageGallery.module.css";

function SummarySection() {
  return (
    <section className={styles.summarySection}>
      <h2 className={styles.summaryHeader}>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/fb85187f433ad7e4082b9293304cce6281a1cc17ad27f92a80972a45753c9b59?placeholderIfAbsent=true&apiKey=536ced9e0c9a4584a7ff64aa811182cc"
          alt=""
          className={styles.summaryIcon}
        />
        <span className={styles.summaryText}>Summary</span>
      </h2>
    </section>
  );
}

export default SummarySection;
