/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ImageGallery.module.css";

function TopBar() {
  return (
    <nav className={styles.topBar}>
      <div className={styles.tabContainer}>
        <div className={styles.tabWrapper}>
          <div className={styles.tabContent}>
            <div className={styles.selectStatus}>
              <label htmlFor="statusSelect" className={styles.selectLabel}>
                <span className={styles.selectValue}>Select Status</span>
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/c871a289652c6d802888a1bd20264fb882bd7cce8787a23ed579e9997aa10791?placeholderIfAbsent=true&apiKey=536ced9e0c9a4584a7ff64aa811182cc"
                  alt=""
                  className={styles.selectIcon}
                />
              </label>
            </div>
          </div>
        </div>
      </div>
    </nav>
  );
}

export default TopBar;
